site_name: HDZero VTX Docs

theme:
  name: readthedocs
  locale: en
  navigation_depth: 3
  include_sidebar: false
  icon:
    repo: fontawesome/brands/git

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 3
      indexing: 'full'

extra:
  version: v2.0

repo_url: https://github.com/hd-zero/hdzero-vtx-docs
repo_name: 'Github'
edit_uri: 'blob/main/docs/'

nav:
  - Home: 'index.md'
  - VTX Target: 'vtx_targets.md'
  - Camera Target: 'camera_targets.md'
  - User Manual: 'vtx_user_manual.md'
  - Troubleshoot: 'vtx_troubleshoot.md'
  - About: 'about.md'